import { Drink } from '@/types/menu';

export const SignatureCocktail: Drink[] = [
  {
    id: 1,
    title: 'Makgeollita',
    description: '',
    volume: '3oz',
    price: 17,
    virgin: false,
    option: false,
  },
  {
    id: 2,
    title: 'How Daechu',
    description: '',
    volume: '2oz',
    price: 16,
    virgin: false,
    option: false,
  },
  {
    id: 3,
    title: 'Hennessy Green Tea',
    description: '',
    volume: '1.5oz',
    price: 15,
    virgin: false,
    option: false,
  },
  {
    id: 4,
    title: 'Yuja Sour',
    description: '',
    volume: '2oz',
    price: 15,
    virgin: true,
    option: false,
  },
  {
    id: 5,
    title: 'Hwayo Mule',
    description: '',
    volume: '2oz',
    price: 15,
    virgin: true,
    option: false,
  },
];

export const Martini: Drink[] = [
  {
    id: 1,
    title: 'Dry martini (vodka,Gin)',
    description: '',
    volume: '2.5oz',
    price: 13,
    virgin: false,
    option: false,
  },
  {
    id: 2,
    title: 'Cosmopolitan',
    description: '',
    volume: '2oz',
    price: 14,
    virgin: false,
    option: false,
  },
  {
    id: 3,
    title: 'KamiKaze',
    description: '',
    volume: '2.5oz',
    price: 14,
    virgin: false,
    option: false,
  },
  {
    id: 4,
    title: 'Lychee Martini',
    description: '',
    volume: '3oz',
    price: 15,
    virgin: false,
    option: false,
  },
  {
    id: 5,
    title: 'Espresso Martini',
    description: '',
    volume: '1.5oz',
    price: 14,
    virgin: false,
    option: false,
  },
  {
    id: 6,
    title: 'Grand Blue',
    description: '',
    volume: '2oz',
    price: 14,
    virgin: false,
    option: false,
  },
  {
    id: 7,
    title: 'Chocolate Martini',
    description: '',
    volume: '3oz',
    price: 15,
    virgin: false,
    option: false,
  },
  {
    id: 8,
    title: 'Agwa Trip',
    description: '',
    volume: '2.5oz',
    price: 15,
    virgin: false,
    option: false,
  },
];

export const OldCocktail: Drink[] = [
  {
    id: 1,
    title: 'Negroni',
    description: '',
    volume: '3oz',
    price: 14,
    virgin: false,
    option: false,
  },
  {
    id: 2,
    title: 'Old Fashioned',
    description: '',
    volume: '2oz',
    price: 14,
    virgin: false,
    option: false,
  },
  {
    id: 3,
    title: 'God Father',
    description: '',
    volume: '2.5oz',
    price: 13,
    virgin: false,
    option: false,
  },
  {
    id: 4,
    title: 'Black Russian',
    description: '',
    volume: '2.5oz',
    price: 13,
    virgin: false,
    option: false,
  },
  {
    id: 5,
    title: 'White Russian',
    description: '',
    volume: '2.5oz',
    price: 13,
    virgin: false,
    option: false,
  },
  {
    id: 6,
    title: 'Tomcollins',
    description: '',
    volume: '2oz',
    price: 13,
    virgin: false,
    option: false,
  },
  {
    id: 7,
    title: 'Cuba Libre',
    description: '',
    volume: '2oz',
    price: 13,
    virgin: false,
    option: false,
  },
];

export const Cocktail: Drink[] = [
  {
    id: 1,
    title: 'Emerald Coast',
    description: '',
    volume: '2oz',
    price: 15,
    virgin: false,
    option: false,
  },
  {
    id: 2,
    title: 'Peach Crush',
    description: '',
    volume: '1.5oz',
    price: 14,
    virgin: true,
    option: false,
  },
  {
    id: 3,
    title: 'East Sea',
    description: '',
    volume: '1.5oz',
    price: 14,
    virgin: false,
    option: false,
  },
  {
    id: 4,
    title: 'Longisland Icetea',
    option: false,
    description: '',
    volume: '2.5oz',
    price: 15,
    virgin: false,
  },
  {
    id: 5,
    title: 'Georgia Peach Icetea',
    description: '',
    volume: '2.5oz',
    price: 15,
    virgin: false,
    option: false,
  },
  {
    id: 6,
    title: 'Mud Slide',
    description: '',
    volume: '2.5oz',
    price: 15,
    virgin: false,
    option: false,
  },
  {
    id: 7,
    title: 'June Bug',
    description: '',
    volume: '2oz',
    price: 15,
    virgin: false,
    option: false,
  },
  {
    id: 8,
    title: 'Midori Sour',
    description: '',
    volume: '2oz',
    price: 14,
    virgin: false,
    option: false,
  },
  {
    id: 9,
    title: 'Blue Hawaiian',
    description: '',
    volume: '2oz',
    price: 15,
    virgin: false,
    option: false,
  },
  {
    id: 10,
    title: 'Pina Colada',
    description: '',
    volume: '1.5oz',
    price: 14,
    virgin: true,
    option: false,
  },
  {
    id: 11,
    title: 'Caesar',
    description: '',
    volume: '1.5oz',
    price: 13,
    virgin: true,
    option: false,
  },
  {
    id: 12,
    title: 'Sangria (Red,White)',
    description: '',
    volume: '4oz',
    price: 14,
    virgin: false,
    option: false,
  },
  {
    id: 13,
    title: 'Mojito',
    description: '',
    volume: '1.5oz',
    price: 15,
    virgin: true,
    option: false,
  },
  {
    id: 14,
    title: 'Cassis Funky',
    description: '',
    volume: '1.5oz',
    price: 14,
    virgin: false,
    option: false,
  },
  {
    id: 15,
    title: 'Sexy No.1',
    description: '',
    volume: '1.5oz',
    price: 14,
    virgin: false,
    option: false,
  },
  {
    id: 16,
    title: 'Special Mai Tai',
    description: '',
    volume: '2.5oz',
    price: 15,
    virgin: false,
    option: false,
  },
  {
    id: 17,
    title: 'Amaretto Sour',
    description: '',
    volume: '2oz',
    price: 14,
    virgin: false,
    option: false,
  },
];

export const DraftBeer: Drink[] = [
  {
    id: 1,
    title: 'Sapporo',
    description: '',
    volume: ['16oz', '$8', '60oz', '$29'],
    price: [8, 29],
    virgin: false,
    option: true,
  },
  {
    id: 2,
    title: 'Sleeman',
    description: '',
    volume: ['16oz', '$8', '60oz', '$29'],
    price: [8, 29],
    virgin: false,
    option: true,
  },
  {
    id: 3,
    title: 'Wraspberry Ale [Wild Rose]',
    description: '',
    volume: ['16oz', '$7', '60oz', '$24'],
    price: [7, 24],
    virgin: false,
    option: true,
  },
  {
    id: 4,
    title: 'Sun Scout [Wild Rose]',
    description: '',
    volume: ['16oz', '$7', '60oz', '$24'],
    price: [7, 24],
    virgin: false,
    option: true,
  },
];

export const ImportBeer: Drink[] = [
  {
    id: 1,
    title: 'Erdinger Weissbrau',
    description: '',
    volume: '500ml',
    price: 11,
    virgin: false,
    option: false,
  },
  {
    id: 2,
    title: 'Guinness',
    description: '',
    volume: '500ml',
    price: 11,
    virgin: false,
    option: false,
  },
];
export const KoreanBeer: Drink[] = [
  {
    id: 1,
    title: 'Kloud',
    description: '',
    volume: '500ml',
    price: 11,
    virgin: false,
    option: false,
  },
  {
    id: 2,
    title: 'Cass',
    description: '',
    volume: '500ml',
    price: 9,
    virgin: false,
    option: false,
  },
];

export const LocalBeer: Drink[] = [
  {
    id: 1,
    title: 'Okami Kasu',
    description: '',
    volume: '355ml',
    price: 7,
    virgin: false,
    option: false,
  },
  {
    id: 2,
    title: 'One Love Hasy ISA',
    description: '',
    volume: '473ml',
    price: 9,
    virgin: false,
    option: false,
  },
  {
    id: 3,
    title: 'Luminosity',
    description: '',
    volume: '473ml',
    price: 9,
    virgin: false,
    option: false,
  },
  {
    id: 4,
    title: 'Tokyo Drift',
    description: '',
    volume: '473ml',
    price: 9,
    virgin: false,
    option: false,
  },
  {
    id: 5,
    title: 'Grapefruit Radler',
    description: '',
    volume: '473ml',
    price: 10,
    virgin: false,
    option: false,
  },
  {
    id: 6,
    title: 'The Wolf',
    description: '',
    volume: '473ml',
    price: 10,
    virgin: false,
    option: false,
  },
  {
    id: 7,
    title: 'Coors Light',
    description: '',
    volume: '473ml',
    price: 10,
    virgin: false,
    option: false,
  },
  {
    id: 8,
    title: 'Moosehead',
    description: '',
    volume: '473ml',
    price: 10,
    virgin: false,
    option: false,
  },
];

export const Whiskey: Drink[] = [
  {
    id: 1,
    title: 'Royal Salute 21Y',
    description: '',
    volume: '750ml',
    price: 355,
    virgin: false,
    option: false,
  },
  {
    id: 2,
    title: 'Highland Park 18Y',
    description: '',
    volume: '750ml',
    price: 535,
    virgin: false,
    option: false,
  },
  {
    id: 3,
    title: 'Macallan 12Y',
    description: '',
    volume: '750ml',
    price: 255,
    virgin: false,
    option: false,
  },
  {
    id: 4,
    title: 'Hennessy V.S',
    description: '',
    volume: '750ml',
    price: 180,
    virgin: false,
    option: false,
  },
  {
    id: 5,
    title: 'Hennessy V.S.O.P',
    description: '',
    volume: '750ml',
    price: 240,
    virgin: false,
    option: false,
  },
  {
    id: 6,
    title: 'Hennessy X.O',
    description: '',
    volume: '750ml',
    price: 655,
    virgin: false,
    option: false,
  },
  {
    id: 7,
    title: 'Glenfidich 12Y',
    description: '',
    volume: '750ml',
    price: 200,
    virgin: false,
    option: false,
  },
  {
    id: 8,
    title: 'Glenfiddich 21Y',
    description: '',
    volume: '750ml',
    price: 795,
    virgin: false,
    option: false,
  },
  {
    id: 9,
    title: 'Alberta Premium',
    description: '',
    volume: '750ml',
    price: 220,
    virgin: false,
    option: false,
  },
  {
    id: 10,
    title: 'Johnnie Walker Blue',
    description: '',
    volume: '750ml',
    price: 725,
    virgin: false,
    option: false,
  },
];

export const WhiteWine: Drink[] = [
  {
    id: 1,
    title: 'Fantini Pinot Grigio ',
    description: '',
    volume: ['5oz', '$8', '9oz', '$11', 'bottle', '$34'],
    price: [8, 11, 34],
    virgin: false,
    option: true,
  },
  {
    id: 2,
    title: 'Fetzer Gewurztraminer ',
    description: '',
    volume: ['5oz', '$10', '9oz', '$16', 'bottle', '$45'],
    price: [10, 16, 45],
    virgin: false,
    option: true,
  },
  {
    id: 3,
    title: 'Baglio Oro Guari Inzolia',
    description: '',
    volume: ['5oz', '$11', '9oz', '$18', 'bottle', '$51'],
    price: [11, 18, 51],
    virgin: false,
    option: true,
  },
  {
    id: 4,
    title: 'WhiteHaven Sauvignon Blanc',
    description: '',
    volume: ['5oz', '$13', '9oz', '$23', 'bottle', '$62'],
    price: [13, 23, 62],
    virgin: false,
    option: true,
  },
];

export const RedWine: Drink[] = [
  {
    id: 1,
    title: 'Bouchard Aine Pinot Noir',
    description: '',
    volume: ['5oz', '$7', '9oz', '$10', 'bottle', '$32'],
    price: [7, 10, 32],
    virgin: false,
    option: true,
  },
  {
    id: 2,
    title: 'Les Jamelles Syrah',
    description: '',
    volume: ['5oz', '$11', '9oz', '$18', 'bottle', '$49'],
    price: [11, 18, 49],
    virgin: false,
    option: true,
  },
  {
    id: 3,
    title: 'Monasterio Gran Reserva',
    description: '',
    volume: ['5oz', '$12', '9oz', '$22', 'bottle', '$52'],
    price: [12, 22, 52],
    virgin: false,
    option: true,
  },
  {
    id: 4,
    title: 'El enemigo cabernet Franc',
    description: '',
    volume: ['bottle', '$101'],
    price: 101,
    virgin: false,
    option: true,
  },
];

export const RoseWine: Drink[] = [
  {
    id: 1,
    title: `Famille perrin L'oustalet reserve rose`,
    description: '',
    volume: ['5oz', '$8', '9oz', '$12', 'bottle', '$34'],
    price: [8, 12, 34],
    virgin: false,
    option: true,
  },
];

export const BubblyWine: Drink[] = [
  {
    id: 1,
    title: 'Cava Castelfino brut',
    description: '',
    volume: 'bottle',
    price: 41,
    virgin: false,
    option: false,
  },
  {
    id: 2,
    title: 'Giusti Prosecco Rosalia Doc',
    description: '',
    volume: 'bottle',
    price: 60,
    virgin: false,
    option: false,
  },
];

export const Sake: Drink[] = [
  {
    id: 1,
    title: 'Dassai Junmai Dai-Ginjo "45"',
    description: '',
    volume: ['300ml', '$55'],
    price: 55,
    virgin: false,
    option: true,
  },
  {
    id: 2,
    title: 'Brewmasters Choice Honjozo',
    description: '',
    volume: ['5oz', '$11', '9oz', '$19', 'bottle', '$53'],
    price: [11, 19, 53],
    virgin: false,
    option: true,
  },
  {
    id: 3,
    title: 'Kawatsuru Sanuki Cloudy',
    description: '',
    volume: ['5oz', '$13', '9oz', '$23', 'bottle', '$62'],
    price: [13, 23, 62],
    virgin: false,
    option: true,
  },
  {
    id: 4,
    title: 'ALZUHOMARE Junmai Daiginjo Kiwami',
    description: '',
    volume: ['5oz', '$16', '9oz', '$28', 'bottle', '$78'],
    price: [16, 28, 78],
    virgin: false,
    option: true,
  },
];
export const OriginalSoju: Drink[] = [
  {
    id: 1,
    title:
      'Chamisul Fresh, Chumchurum Original, Jinro is back,Saero, Hanlasan21',
    description: '',
    volume: '12oz',
    price: 18,
    virgin: false,
    option: false,
  },
];
export const FlavouredSoju: Drink[] = [
  {
    id: 1,
    title:
      'Yogurt, Citron, Peach, Grape, Apple, Strawberry, Mango, Lychee, Plum',
    description: '',
    volume: '12oz',
    price: 18,
    virgin: false,
    option: false,
  },
];

export const CocktailSoju: Drink[] = [
  {
    id: 1,
    title: 'Watermelon, Strawberry, Pineapple, Peach, Lemon, Cherry',
    description: '',
    volume: '6oz',
    price: 18,
    virgin: false,
    option: false,
  },
];

export const Makgeolli: Drink[] = [
  {
    id: 1,
    title:
      'Kooksoondang OG, Chestnut Makgeolli, Banana Makgeolli, WhiteGrape Makgeolli',
    description: '',
    volume: '750ml',
    price: 18,
    virgin: false,
    option: false,
  },
];

export const PremiumSoju: Drink[] = [
  {
    id: 1,
    title: 'Daejangbu Premium',
    description: '',
    volume: ['2oz', '$10', '375ml', '$53'],
    price: [10, 53],
    virgin: false,
    option: true,
  },
  {
    id: 2,
    title: 'Hwayo 25',
    description: '',
    volume: ['2oz', '$10', '375ml', '$53'],
    price: [10, 53],
    virgin: false,
    option: true,
  },
  {
    id: 3,
    title: 'Hwayo 41',
    description: '',
    volume: ['2oz', '$14', '750ml', '$170'],
    price: [14, 170],
    virgin: false,
    option: true,
  },
  {
    id: 4,
    title: 'Hwayo 53',
    description: '',
    volume: ['2oz', '$19', '500ml', '$170'],
    price: [19, 170],
    virgin: false,
    option: true,
  },
];

export const OtherSoju: Drink[] = [
  {
    id: 1,
    title: 'Bokbunja',
    description: '',
    volume: '375ml',
    price: 19,
    virgin: false,
    option: false,
  },
  {
    id: 2,
    title: 'Baeksejoo',
    description: '',
    volume: '375ml',
    price: 19,
    virgin: false,
    option: false,
  },
  {
    id: 3,
    title: 'Seljoongmae',
    description: '',
    volume: '375ml',
    price: 19,
    virgin: false,
    option: false,
  },
];
export const NonAlcoholic: Drink[] = [
  {
    id: 1,
    title:
      'Pop(Can) - Coke | Diet Coke | Ginger ale | Sprite | Iced tea | Club Soda | Tonic Water',
    description: '',
    volume: '',
    price: 3,
    virgin: false,
    option: false,
  },
  {
    id: 2,
    title: 'Juice - Orange | Pineapple | Cranberry | Apple',
    description: '',
    volume: '',
    price: 4,
    virgin: false,
    option: false,
  },
  {
    id: 3,
    title: 'Perrier Sparkiling Water',
    description: '',
    volume: '',
    price: 4,
    virgin: false,
    option: false,
  },
  {
    id: 4,
    title: 'Maesil (Green Plum) Soda',
    description: '',
    volume: '',
    price: 6,
    virgin: false,
    option: false,
  },
  {
    id: 5,
    title: 'Peach Jasmine Tea',
    description: '',
    volume: '',
    price: 7,
    virgin: false,
    option: false,
  },
  {
    id: 6,
    title: 'Shirley Temple',
    description: '',
    volume: '',
    price: 7,
    virgin: false,
    option: false,
  },
  {
    id: 7,
    title: 'Housemade Lemonade - Lemon | Orange | Grapefruit | Yuja',
    description: '',
    volume: '',
    price: 8,
    virgin: false,
    option: false,
  },
];

export const Coffee: Drink[] = [
  {
    id: 1,
    title: 'Espresso',
    description: '',
    volume: '2oz',
    price: 3.5,
    virgin: false,
    option: false,
  },
  {
    id: 2,
    title: 'Americano',
    description: '',
    volume: '12oz',
    price: 4.5,
    virgin: false,
    option: false,
  },
  {
    id: 3,
    title: 'Flat White',
    description: '',
    volume: '5oz',
    price: 5.25,
    virgin: false,
    option: false,
  },
  {
    id: 4,
    title: 'Cappuccino',
    description: '',
    volume: '8oz',
    price: 5.5,
    virgin: false,
    option: false,
  },
  {
    id: 5,
    title: 'Latte',
    description: '',
    volume: '12oz',
    price: 6,
    virgin: false,
    option: false,
  },
  {
    id: 6,
    title: 'Flavored Latte - Vanilla | Caramel } Hazelnut',
    description: '',
    volume: '12oz',
    price: 6.75,
    virgin: false,
    option: false,
  },
];

export const Tea: Drink[] = [
  {
    id: 1,
    title: 'Tea Latte - Matcha | Chai | London Fog',
    description: '',
    volume: '12oz',
    price: 6,
    virgin: false,
    option: false,
  },
  {
    id: 2,
    title: 'Tea - Jasmine | Earl Grey | Redberry',
    description: '',
    volume: '12oz',
    price: 4,
    virgin: false,
    option: false,
  },
  {
    id: 3,
    title: 'Korean Tea - Yuja | Jujube | Ginger',
    description: '',
    volume: '12oz',
    price: 4,
    virgin: false,
    option: false,
  },
];
